### PR TITLE
Switch to storing id

### PR DESCRIPTION
**Pull request by stevelacey**
Switch to storing the id instead of url, same as https://github.com/Media24si/nova-youtube-field

### CODE REVIEW

**Comment by stevelacey** [comment]
@tanjemark can you merge and tag this so I don't have to work out how to install my fork? 🙃

**Comment by tanjemark** [comment]
No, require your fork or make it optionally between ID and full URL!

https://stackoverflow.com/questions/13498519/how-to-require-a-fork-with-composer

**Review by tanjemark — COMMENTED** [review]
Make it optionally between ID and full URL!

**Comment by stevelacey** [comment]
1. Don’t talk to your contributors like this
2. If I do that ID should be the default. Is that ok?

**Comment by stevelacey** [comment]
@tanjemark I am happy to make that change and submit another PR, is ID as default ok? That’s what developers would typically expect.

**Pull request closed without merging**
